select ename, hiredate, sal, lag(sal,1,0)over (order by hiredate) "LAG"
from emp;

select * from(select deptno, job, empno from emp)
pivot(count(empno) for job in ('CLERK' as "CLERK", 'MANAGER' AS "MANAGER", 'PRESIDENT' AS "PRESIDENT", 'ANALYST' AS "ANSLYST", 'SALESMAN' AS "SALESMAN"))
order by deptno;

select max(sal)as"MAX", min(sal)AS"MIN"
from emp;

select* from emp;

--1
SELECT max(SAL+NVL(COMM,0))AS "MAX" , MIN(SAL+NVL(COMM,0))AS"MIN", ROUND(AVG(SAL+NVL(COMM,0)),1)AS"AVG"
FROM EMP;

SELECT BIRTHDAY
FROM STUDENT;


--2
SELECT COUNT(*) ||'EA' AS "TOTAL",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '01', 0))||'EA' AS "JAN",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '02', 0))||'EA' AS "FEB",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '03', 0))||'EA' AS "MAR",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '04', 0))||'EA' AS "APR",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '05',0))||'EA' AS "MAY",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '06', 0))||'EA' AS "JUN",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '07', 0))||'EA' AS "JUL",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '08', 0))||'EA' AS "AUG",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '09', 0))||'EA' AS "SEP",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '10', 0))||'EA' AS "OCT",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '11', 0))||'EA' AS "NOV",
        COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '12', 0))||'EA' AS "DEC"
FROM STUDENT;

SELECT TEL
FROM STUDENT;

SELECT COUNT(*) AS "TOTAL"
FROM STUDENT;


--3
SELECT COUNT(*) AS "TOTAL", 
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',0)) AS "SEOUL",
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'031',0)) AS "GYEONGGI",
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'051',0)) AS "BUSAN",
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'052',0)) AS "ULSANN",
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'053',0)) AS "DAEGU",
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'055',0)) AS "GYEONGNAM"
FROM STUDENT;

INSERT INTO EMP(EMPNO,DEPTNO,ENAME,SAL)
2 VALUES(1000,10,'TIGER',3600);
INSERT INTO EMP(EMPNO,DEPTNO,ENAME,SAL)
2 VALUES(2000,30,'CAT',3000);
COMMIT;

SET PAGESIZE 50
SELECT EMPNO,ENAME,JOB,SAL 
FROM EMP;
INSERT INTO EMP(EMPNO,DEPTNO,ENAME,SAL)
VALUES(1000,10,'TIGER',3600);
INSERT INTO EMP(EMPNO,DEPTNO,ENAME,SAL)
VALUES(2000,30,'CAT',3000);

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP 
ORDER BY EMPNO;


--4
SELECT DEPTNO,
    SUM(DECODE(JOB,'CLERK',SAL,0))AS"CLERK",
    SUM(DECODE(JOB,'MANAGER',SAL,0))AS"MANAGER",
    SUM(DECODE(JOB,'PRESIDENT',SAL,0))AS"PRESIDENT",
    SUM(DECODE(JOB,'ANALYST',SAL,0))AS"ANALYST",
    SUM(DECODE(JOB,'SALESMAN',SAL,0))AS"SALESMAN",
    SUM(NVL2(JOB,SAL,0))AS"TOTAL"
FROM EMP
GROUP BY ROLLUP(DEPTNO);


--5
SELECT DEPTNO,ENAME,SAL,
    SUM(SAL) OVER(ORDER BY SAL) AS "TOTAL"
FROM EMP;

SELECT DEPTNO, NULL JOB, ROUND(AVG(SAL),1) AVG_SAL, COUNT(*) CNT_EMP
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO, JOB;

SELECT * FROM FRUIT;


--6
select min(decode(name,'apple',price)) as "APPLE",
min(decode(name,'grape',price)) as "GRAPE",
min(decode(name,'orange',price)) as "ORANGE"
FROM FRUIT;


--7
SELECT COUNT(*) ||'EA' ||'('||COUNT(NAME)/COUNT(NAME)*100||'%)' AS "TOTAL", 
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',0))||'EA' ||'('||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',0))/COUNT(NAME)*100||'%)' AS "SEOUL",
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'031',0))||'EA'||'('||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'031',0))/COUNT(NAME)*100||'%)' AS "GYEONGGI",
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'051',0))||'EA'||'('||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'51',0))/COUNT(NAME)*100||'%)' AS "BUSAN",
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'052',0))||'EA'||'('||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'052',0))/COUNT(NAME)*100||'%)' AS "ULSANN",
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'053',0))||'EA'||'('||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'053',0))/COUNT(NAME)*100||'%)' AS "DAEGU",
        COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'055',0))||'EA'||'('||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'055',0))/COUNT(NAME)*100||'%)' AS "GYEONGNAM"
FROM STUDENT;

SELECT * FROM EMP;


--8
SELECT DEPTNO,ENAME,SAL, 
    SUM(SAL) OVER(PARTITION BY DEPTNO ORDER BY SAL) AS "TOTAL"
FROM EMP;

--9
SELECT DEPTNO,ENAME,SAL,
    SUM(SAL)OVER() AS"TOTAL_SAL",
    ROUND(SAL/SUM(SAL)OVER()*100,2) AS "%"
FROM EMP
GROUP BY DEPTNO,ENAME,SAL
ORDER BY SAL DESC;

--10
SELECT DEPTNO,ENAME,SAL,
    SUM(SAL) OVER(PARTITION BY DEPTNO) "SUM_DEPT",
    ROUND(SAL/SUM(SAL) OVER(PARTITION BY DEPTNO)*100,2)AS"%"
FROM EMP
GROUP BY DEPTNO, ENAME, SAL
ORDER BY 1;




SELECT* FROM LOAN;

--11
SELECT L_DATE AS "대출일자",L_CODE AS "대출종목코드",L_QTY AS "대출건수",L_TOTAL AS "대출총액",
    SUM(L_TOTAL) OVER(ORDER BY L_DATE ) AS "누적대출금액"    
FROM LOAN
WHERE L_STORE = 1000;


--12
SELECT L_CODE AS "대출종목코드",L_STORE AS "대출지점",L_DATE AS"대출일자",L_QTY AS"대출건수",L_TOTAL AS"대출액",
    SUM(L_TOTAL) OVER(PARTITION BY L_CODE,L_STORE ORDER BY L_DATE)  AS "누적대출금액"
FROM LOAN;

--13
SELECT L_DATE AS"대출일자", L_CODE AS"대출구분코드", L_QTY AS"대출건수", L_TOTAL AS"대출총액",
    SUM(L_TOTAL) OVER(PARTITION BY L_CODE ORDER BY L_QTY) AS"누적대출금액"
FROM LOAN
WHERE L_STORE = 1000
ORDER BY L_CODE;


--14
SELECT* FROM PROFESSOR;

SELECT DEPTNO, NAME, PAY, 
    SUM(PAY) OVER() AS "TOTAL PAY",
    ROUND(PAY/SUM(PAY) OVER()*100,2) AS "RATIO %"
FROM PROFESSOR
GROUP BY DEPTNO, NAME, PAY
ORDER BY 5 DESC;

--15
SELECT DEPTNO, NAME, PAY, 
    SUM(PAY) OVER(PARTITION BY DEPTNO) AS "TOTAL_DEPTNO",
    ROUND(SUM(PAY)/SUM(PAY) OVER(PARTITION BY DEPTNO)*100,2) AS "RATIO(%)"
FROM PROFESSOR
GROUP BY DEPTNO, NAME, PAY
ORDER BY 1;

--4장 JOIN
SELECT E.EMPNO, E.ENAME, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

SELECT E.EMPNO, E.ENAME, D.DNAME
FROM EMP E JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

SELECT* FROM STUDENT;
SELECT* FROM PROFESSOR;
--ORACLE JOIN
SELECT S.NAME "STU_NAME", P.NAME "PROF_NAME"
FROM STUDENT S, PROFESSOR P
WHERE S.PROFNO = P.PROFNO;

--ANSI JOIN
SELECT S.NAME "STU_NAME", P.NAME"PROF_NAME"
FROM STUDENT S JOIN PROFESSOR P 
ON S.PROFNO = P.PROFNO;


--ORACLE JOIN
SELECT S.NAME"STU_NAME", D.DNAME"DEPT_NAME", P.NAME"PROF_NAME"
FROM STUDENT S, DEPARTMENT D, PROFESSOR P
WHERE S.DEPTNO1 = D.DEPTNO
AND S.PROFNO = P.PROFNO;

--ANSI JOIN
SELECT S.NAME"STU_NAME", D.DNAME"DEPT_NAME", P.NAME"PROF_NAME"
FROM STUDENT S JOIN DEPARTMENT D
ON S.DEPTNO1 = D.DEPTNO
JOIN PROFESSOR P
ON S.PROFNO = P.PROFNO;

--ORACLE JOIN
SELECT S.NAME "STU_NAME", P.NAME "PROF_NAME"
FROM STUDENT S, PROFESSOR P
WHERE S.PROFNO = P.PROFNO
AND S.DEPTNO1 = 101;

--비등가조인
SELECT* FROM GIFT;
SELECT* FROM Customer;

SELECT C.GNAME "CUST_NAME", TO_CHAR(C.POINT, '999,999') "POINT", G.GNAME "GIFT_NAME"
FROM CUSTOMER C, GIFT G
WHERE C.POINT BETWEEN G.G_START AND G.G_END;


SELECT * FROM SCORE;
SELECT * FROM HAKJUM;

SELECT S.NAME "STU_NAME", O.TOTAL "SCORE", H.GRADE "CREDIT"
FROM STUDENT S, SCORE O, HAKJUM H
WHERE S.STUDNO = O.STUDNO
AND O.TOTAL >= H.MIN_POINT
AND O.TOTAL <= H.MAX_POINT
ORDER BY SCORE;

--아우터조인 이너조인
--아우터조인
SELECT S.NAME "STU_NAME", P.NAME "PROF_NAME"
FROM STUDENT S, PROFESSOR P
WHERE S.PROFNO = P.PROFNO(+);

SELECT S.NAME "STU_NAME", P.NAME "PROF_NAME"
FROM STUDENT S, PROFESSOR P
WHERE S.PROFNO(+) = P.PROFNO;


--SELF JOIN
SELECT E1.ENAME "ENAME", E2.ENAME "MGR_ENAME"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

--예제01
SELECT * FROM STUDENT;
SELECT * FROM DEPARTMENT;

SELECT S.NAME "STU_NAME", DEPTNO1, D.DNAME "DEPT_NAME"
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPTNO1 = D.DEPTNO;


--예제02
SELECT * FROM EMP2;
SELECT * FROM P_GRADE;

SELECT E.NAME "NAME", E.POSITION "POSITION",TO_CHAR(E.PAY,'999,999,999')"PAY",  TO_CHAR(P.S_PAY,'999,999,999') "LOW PAY", TO_CHAR(P.E_PAY,'999,999,999') "HIGH PAY"
FROM EMP2 E, P_GRADE P
WHERE E.POSITION = P.POSITION;


--예제03
SELECT * FROM EMP2;
SELECT * FROM P_GRADE;

SELECT E.NAME "NAME", TRUNC((SYSDATE - E.BIRTHDAY)/365.0) "AGE",
    E.POSITION "CURR_POSITION", P.POSITION "BE_POSITION"
FROM EMP2 E, P_GRADE P
WHERE TRUNC((SYSDATE - E.BIRTHDAY)/365.0) BETWEEN P.S_AGE AND P.E_AGE;


--예제04
SELECT * FROM CUSTOMER;
SELECT * FROM GIFT;

SELECT C.GNAME "CUST_NAME", C.POINT, G.GNAME "GIFT_NAME"
FROM CUSTOMER C, GIFT G
WHERE G.G_START <= C.POINT
AND G.GNAME = 'Notebook';


--예제05
SELECT * FROM PROFESSOR;

SELECT P1.PROFNO "PROFNO", P1.NAME "NAME", TO_CHAR(P1.HIREDATE,'YYYY/MM/DD') "HIREDATE",
    COUNT(P2.HIREDATE) "COUNT"
FROM PROFESSOR P1, PROFESSOR P2
WHERE P2.HIREDATE(+) < P1.HIREDATE
GROUP BY P1.PROFNO, P1.NAME, P1.HIREDATE
ORDER BY 4;

--예제06
SELECT E1.EMPNO, E1.ENAME,
    TO_CHAR(E1.HIREDATE,'YYYY/MM/DD') "HIREDATE",
    COUNT(E2.HIREDATE) "COUNT"
FROM EMP E1, EMP E2
WHERE E2.HIREDATE(+) < E1.HIREDATE
GROUP BY E1.EMPNO, E1.ENAME, E1.HIREDATE
ORDER BY 4;

